export const data = {
  products: [
    {
      name: 'Free Shirts',
      slug: 'free-shirt',
      category: 'Shirts',
      img: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Fit Shirts',
      slug: 'fit-shirt',
      category: 'Shirts',
      img: '/images/shirt2.jpg',
      price: 80,
      brand: 'Adidas',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Slim Shirts',
      slug: 'slim-shirt',
      category: 'Shirts',
      img: '/images/shirt3.jpg',
      price: 90,
      brand: 'Raymond',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Gold Pants',
      slug: 'golf-pants',
      category: 'Pants',
      img: '/images/pants1.jpg',
      price: 75,
      brand: 'Raymond',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Pants',
    },
    {
      name: 'Fit Pants',
      slug: 'fit-pants',
      category: 'Pants',
      img: '/images/pants2.jpg',
      price: 75,
      brand: 'Zara',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Pants',
    },
    {
      name: 'Classic Pants',
      slug: 'classic-pants',
      category: 'Pants',
      img: '/images/pants3.jpg',
      price: 75,
      brand: 'Casely',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Pants',
    },
  ],
};
